### ISSUE TITLE
KeepAlive dosent work

### ISSUE THREAD

**Issue by cojaco** [kammerer/tipTipX#1]
When I set KeepAlive to true I only see the first tooltip, the other tooltip dont appear.
Also most of the jquery javascripts seem to not work than.

**Comment by kammerer** [comment]
Sorry, I do not support this anymore - there are probably better jQuery tooltip plugins available at this moment. Anyway, thanks for the feedback.

**Comment by cojaco** [comment]
thanks, no problem, i found poshytip.
